/* ============================================================
   VIEMAG — Data Layer  (AUTO-GENERATED by supabase/functions/export-site-data)
   Source of truth: Supabase VIEMAG project. DO NOT edit by hand —
   edit in /admin and it re-exports automatically on save.
   Public fields only; internal margin/stock columns are not even SELECTed.
   zh (Traditional) is the base; zh-Hans auto-converts at runtime.
   ============================================================ */
window.DB = {
  "categories": [
    {
      "id": "vehicle",
      "cat": "V",
      "status": "published",
      "art": "dash",
      "name": {
        "en": "Vehicle",
        "vi": "Ô tô",
        "id": "Mobil",
        "zh": "車用生態"
      },
      "desc": {
        "en": "Drive, navigate, one-hand dock. The flagship line built for daily commutes.",
        "vi": "Lái xe, dẫn đường, hút chắc không rơi — dòng chủ lực của VIEMAG.",
        "id": "Berkendara, navigasi, tempel satu tangan. Lini unggulan untuk komuter harian.",
        "zh": "開車導航、單手取放、穩固不掉，VIEMAG 的旗艦產品線。"
      },
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "id": "desk",
      "cat": "D",
      "status": "published",
      "art": "deskcharge",
      "name": {
        "en": "Desk",
        "vi": "Để bàn",
        "id": "Meja",
        "zh": "桌面生態"
      },
      "desc": {
        "en": "A tidier desk at work, a lighter bag on the road.",
        "vi": "Bàn làm việc gọn gàng, đi công tác nhẹ hành lý.",
        "id": "Meja kerja lebih rapi, tas lebih ringan saat bepergian.",
        "zh": "工作桌面更整潔，出差行李更輕。"
      },
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "id": "ride",
      "cat": "R",
      "status": "future",
      "art": "ride",
      "name": {
        "en": "Ride",
        "vi": "Xe máy",
        "id": "Motor",
        "zh": "騎行生態"
      },
      "desc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "id": "studio",
      "cat": "S",
      "status": "future",
      "art": "tripod",
      "name": {
        "en": "Studio",
        "vi": "Sáng tạo",
        "id": "Studio",
        "zh": "創作生態"
      },
      "desc": {
        "en": "Desk, bedside and creator stands — coming soon.",
        "vi": "Giá đỡ bàn làm việc, đầu giường và quay video — sắp ra mắt.",
        "id": "Dudukan meja, samping ranjang, dan kreator — segera hadir.",
        "zh": "桌面、床邊與創作立架，即將推出。"
      },
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "id": "battery",
      "cat": "B",
      "status": "future",
      "art": "powerbank",
      "name": {
        "en": "Battery",
        "vi": "Sạc dự phòng",
        "id": "Power Bank",
        "zh": "行動電源生態"
      },
      "desc": {
        "en": "Snap-on power banks for the road — coming soon.",
        "vi": "Pin dự phòng hút dán sau máy — sắp ra mắt.",
        "id": "Power bank tempel untuk perjalanan — segera hadir.",
        "zh": "吸附即充的行動電源，即將推出。"
      },
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "id": "portable",
      "cat": "P",
      "status": "published",
      "art": "fold",
      "name": {
        "en": "Portable",
        "vi": "Di động",
        "id": "Portabel",
        "zh": "隨身行動生態"
      },
      "desc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "id": "accessory",
      "cat": "A",
      "status": "published",
      "art": "ring",
      "name": {
        "en": "Accessory",
        "vi": "Phụ kiện",
        "id": "Aksesori",
        "zh": "擴充配件生態"
      },
      "desc": {
        "en": "Adapter rings and cases that bring any phone into the magnetic system.",
        "vi": "Vòng chuyển đổi và ốp lưng giúp mọi điện thoại dùng được hệ nam châm.",
        "id": "Cincin adaptor dan casing yang membawa ponsel apa pun ke sistem magnetik.",
        "zh": "轉接環與手機殼，讓任何手機都能進入磁吸系統。"
      },
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    }
  ],
  "scenarios": [
    {
      "id": "driving",
      "status": "primary",
      "icon": "car",
      "name": {
        "en": "Driving & Commute",
        "vi": "Lái xe & Di chuyển",
        "id": "Berkendara & Komuter",
        "zh": "通勤・行動"
      },
      "desc": {
        "en": "Stable navigation, one-hand dock and release, no drops under hard braking.",
        "vi": "Dẫn đường ổn định, lấy – gắn một tay, không lo rơi khi phanh gấp.",
        "id": "Navigasi stabil, pasang–lepas satu tangan, tidak jatuh saat mengerem mendadak.",
        "zh": "導航穩定、單手取放，急煞不掉落。"
      },
      "pain": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "img": null,
      "combo": [
        "V02",
        "VQ10",
        "A01"
      ]
    },
    {
      "id": "deskwork",
      "status": "secondary",
      "icon": "desk",
      "name": {
        "en": "Work & Office",
        "vi": "Làm việc & Văn phòng",
        "id": "Kerja & Kantor",
        "zh": "工作・辦公"
      },
      "desc": {
        "en": "Charge through video calls with a cable-free desk.",
        "vi": "Vừa sạc vừa họp video, bàn làm việc không dây rối.",
        "id": "Mengisi daya sambil rapat video, meja tanpa kabel semrawut.",
        "zh": "邊充電邊視訊，桌面沒有線材糾纏。"
      },
      "pain": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "img": null,
      "combo": [
        "D01",
        "D02",
        "A02"
      ]
    },
    {
      "id": "travel",
      "status": "supporting",
      "icon": "plane",
      "name": {
        "en": "Travel & Business Trips",
        "vi": "Công tác & Du lịch",
        "id": "Perjalanan & Dinas",
        "zh": "差旅・出差"
      },
      "desc": {
        "en": "One folding charger replaces a pouch full of cables.",
        "vi": "Một củ sạc gập gọn thay cả túi dây cáp.",
        "id": "Satu pengisi lipat menggantikan sekantong kabel.",
        "zh": "一顆折疊充電器，取代一整包線材。"
      },
      "pain": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "img": null,
      "combo": [
        "PQ02",
        "P01",
        "A01"
      ]
    },
    {
      "id": "home",
      "status": "future",
      "icon": "home",
      "name": {
        "en": "Home & Leisure",
        "vi": "Ở nhà & Thư giãn",
        "id": "Rumah & Santai",
        "zh": "居家・休憩"
      },
      "desc": {
        "en": "Movies, kitchen, family charging — one magnetic system shared at home.",
        "vi": "Xem phim, vào bếp, cả nhà dùng chung một hệ nam châm.",
        "id": "Film, dapur, pengisian keluarga — satu sistem magnetik dibagi di rumah.",
        "zh": "追劇、下廚，全家共用同一套磁吸系統。"
      },
      "pain": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "img": null,
      "combo": [
        "D01",
        "BQ01"
      ]
    },
    {
      "id": "outdoor",
      "status": "supporting",
      "icon": "sun",
      "name": {
        "en": "Outdoors & trips",
        "vi": "Ngoài trời & du ngoạn",
        "id": "Luar ruang & jalan-jalan",
        "zh": "戶外・出遊"
      },
      "desc": {
        "en": "No power outlet for hours — the difference from business travel is bringing your own.",
        "vi": "Không có ổ điện trong nhiều giờ — khác với công tác, bạn phải tự mang điện theo.",
        "id": "Tanpa colokan listrik berjam-jam — bedanya dengan perjalanan bisnis: bawa daya sendiri.",
        "zh": "一整天沒有插座可用——與差旅的差別就在於電要自己帶。"
      },
      "pain": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "img": null,
      "combo": [
        "BQ01",
        "V08",
        "A01"
      ]
    },
    {
      "id": "creator",
      "status": "future",
      "icon": "camera",
      "name": {
        "en": "Record & create",
        "vi": "Ghi lại & sáng tạo",
        "id": "Rekam & berkarya",
        "zh": "紀錄・創作"
      },
      "desc": {
        "en": "Filming, livestreaming and tripod work — for anyone recording, not just professionals.",
        "vi": "Quay phim, livestream và chân máy — cho bất kỳ ai muốn ghi lại, không chỉ dân chuyên.",
        "id": "Merekam, livestream, dan tripod — untuk siapa saja, bukan hanya profesional.",
        "zh": "拍攝、直播與腳架應用。「紀錄」不限專業創作者——拍小孩、錄一趟路程都算。"
      },
      "pain": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "img": null,
      "combo": [
        "S01",
        "A01"
      ]
    }
  ],
  "products": [
    {
      "sku": "A01",
      "slug": "a01",
      "status": "published",
      "category": "accessory",
      "subCategory": "interface",
      "art": "suction",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [],
      "price": null,
      "rating": null,
      "reviews": 0,
      "badge": null,
      "name": {
        "en": "Vacuum-Mounted Magnetic Holder",
        "vi": "Giá đỡ từ tính dán chân không",
        "id": "Dudukan Magnetik yang Menempel dengan Vakum",
        "zh": "真空黏貼磁吸支架"
      },
      "claim": {
        "en": "1. TPU Soft Leather Base\n2. N52 Magnetic Clasp\n3. Foldable\n4. 360-degree rotation + dual 180-degree rotation",
        "vi": "1. Đế bằng da mềm TPU\n2. Nam châm N52\n3. Có thể gập lại được\n4. Có thể xoay 360 độ + xoay kép 180 độ",
        "id": "1. Alas dari bahan TPU yang lembut\n2. Penahan magnetik N52\n3. Dapat dilipat\n4. Dapat berputar 360 derajat + dua putaran 180 derajat",
        "zh": "1.TPU 軟皮底座\n2.N52磁吸\n3.可折疊\n4.可 360 度+雙 180 旋轉"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "spec": "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1788598902990-zfonzq2q7ae-A1__6_.jpg",
      "img": "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1788598873187-9wo98mugx57-A1__3_.jpg"
    },
    {
      "sku": "A02",
      "slug": "a02",
      "status": "published",
      "category": "accessory",
      "subCategory": "interface",
      "art": "case",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [],
      "price": 14.9,
      "rating": null,
      "reviews": 0,
      "badge": null,
      "name": {
        "en": "VIEMAG Case + Ring Bundle",
        "vi": "Combo ốp lưng + vòng nam châm VIEMAG",
        "id": "Bundel Casing + Cincin VIEMAG",
        "zh": "VIEMAG 手機殼＋轉接環組合"
      },
      "claim": {
        "en": "A protective case with the magnet ring pre-aligned for maximum grip.",
        "vi": "Ốp bảo vệ kèm vòng nam châm định vị sẵn — tương thích tối đa.",
        "id": "Casing pelindung dengan cincin magnet yang sudah presisi untuk cengkeraman maksimal.",
        "zh": "保護殼內建對位磁環，相容性一次到位。"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "sku": "BQ01",
      "slug": "bq01",
      "status": "future",
      "category": "battery",
      "subCategory": "power",
      "art": "powerbank",
      "qi": "compatible",
      "qiId": null,
      "watt": "15W",
      "mount": [],
      "price": null,
      "rating": null,
      "reviews": 0,
      "badge": "soon",
      "name": {
        "en": "VIEMAG Magnetic Power Bank 10K",
        "vi": "Pin nam châm VIEMAG 10.000mAh",
        "id": "Power Bank Magnetik VIEMAG 10K",
        "zh": "VIEMAG 磁吸行動電源 10K"
      },
      "claim": {
        "en": "Snaps to the back and charges wirelessly on the move — coming soon.",
        "vi": "Hút dán sau máy, sạc không dây khi đang di chuyển — sắp ra mắt.",
        "id": "Menempel di belakang dan mengisi nirkabel saat bergerak — segera hadir.",
        "zh": "吸附機背、行進間無線充電，即將推出。"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "sku": "D01",
      "slug": "d01",
      "status": "future",
      "category": "desk",
      "subCategory": "stands",
      "art": "stand",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [
        "desktop"
      ],
      "price": null,
      "rating": null,
      "reviews": 0,
      "badge": "soon",
      "name": {
        "en": "VIEMAG Desktop Magnetic Stand",
        "vi": "Giá đỡ bàn nam châm VIEMAG",
        "id": "Dudukan Magnetik Meja VIEMAG",
        "zh": "VIEMAG 桌面磁吸立架"
      },
      "claim": {
        "en": "Raises the phone to eye level, rotates portrait to landscape — coming soon.",
        "vi": "Nâng máy lên tầm mắt, xoay dọc ngang tuỳ ý — sắp ra mắt.",
        "id": "Mengangkat ponsel setinggi mata, memutar potret ke lanskap — segera hadir.",
        "zh": "手機抬升至視線高度、直橫向自由旋轉，即將推出。"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "sku": "D02",
      "slug": "d02",
      "status": "future",
      "category": "desk",
      "subCategory": "stands",
      "art": "stand",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [
        "desktop"
      ],
      "price": null,
      "rating": null,
      "reviews": 0,
      "badge": "soon",
      "name": {
        "en": "VIEMAG Magnetic Dual Device Stand",
        "vi": "Giá đỡ từ tính hai thiết bị VIEMAG",
        "id": "VIEMAG Dudukan Perangkat Ganda Magnetik",
        "zh": "VIEMAG 磁吸式雙裝置支架"
      },
      "claim": {
        "en": "One stand, two devices, maximum efficiency.",
        "vi": "Một giá đỡ, hai thiết bị, hiệu quả tối đa.",
        "id": "Satu dudukan, dua perangkat, efisiensi maksimal.",
        "zh": "一個底座，兩台裝置，效率最大化。"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 7,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "sku": "D06",
      "slug": "d06",
      "status": "future",
      "category": "desk",
      "subCategory": "stands",
      "art": "stand",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [
        "magsafe",
        "desktop"
      ],
      "price": null,
      "rating": null,
      "reviews": 0,
      "badge": null,
      "name": {
        "en": "E1 | VIEMAG",
        "vi": "",
        "id": "",
        "zh": "超薄磁吸手機座 | VIEMAG"
      },
      "claim": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": "磁吸\n270度旋轉支架，多角度調節觀看。\n可折疊"
      },
      "reports": [],
      "gallery": [
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/E1/1788600879748-C9-006-std-Perspective.PNG",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/E1/1788600881946-C9-_-016-std-Perspective.denoiser.PNG",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/E1/1788600883925-C9-020-std-Perspective-1.webp",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/E1/1788600887998-C9-020-std-Perspective.webp",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/E1/1788600891814-C9-022-1.webp",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/E1/1788600896386-C9-022.webp"
      ],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "accessories": {
        "en": [],
        "vi": [],
        "id": [],
        "zh": [
          "酒精棉片",
          "黏貼式磁吸環*1",
          "保護貼",
          "定位卡",
          "3M金屬座"
        ]
      },
      "img": "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/E1/1788600877443-C9-008-std-Perspective-0.png"
    },
    {
      "sku": "P01",
      "slug": "p01",
      "status": "future",
      "category": "portable",
      "subCategory": "travel",
      "art": "stand",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [
        "suction"
      ],
      "price": 8.9,
      "rating": null,
      "reviews": 0,
      "badge": null,
      "name": {
        "en": "360° Multi-Purpose Magnetic Travel Phone Mount | VIEMAG",
        "vi": "Giá Đỡ Điện Thoại Từ Tính Kẹp Đa Năng Du Lịch 360° | VIEMAG",
        "id": "Dudukan Ponsel Magnetik Serbaguna dengan Penjepit untuk Perjalanan 360° | VIEMAG",
        "zh": "360° 多功能磁吸式旅行手機支架 | VIEMAG"
      },
      "claim": {
        "en": "Compatible with many types of smartphones.\nCompatible with iPhones and Apple-branded MagSafe cases.\nDual-swivel design, allowing for flexible adjustment to multiple angles of use.\nRotates 360°, making it easy to switch between portrait and landscape modes.\nPull the D-ring at the bottom to quickly clip it to a dining table, tray table, handle, and many other surfaces; ideal for use on airplanes, high-speed trains, cars, and outdoors.\nFeatures a powerful magnet on the back that attaches to iron-containing metal surfaces, making it convenient for navigation, taking selfies, livestreaming, or watching videos hands-free.\nFeatures a standard 1/4\"-20 camera thread, compatible with tripods and selfie sticks.\nCompact, lightweight, and easy to carry—perfect for work, travel, or everyday use.",
        "vi": "Phù hợp với nhiều loại điện thoại thông minh.\nTương thích với iPhone và ốp lưng MagSafe chính hãng Apple.\nThiết kế trục xoay kép, linh hoạt điều chỉnh nhiều góc sử dụng.\nXoay 360°, dễ dàng chuyển đổi giữa chế độ dọc và ngang.\nKéo vòng chữ D phía dưới để kẹp nhanh vào bàn ăn, bàn khay, tay cầm và nhiều vị trí khác; phù hợp sử dụng trên máy bay, tàu cao tốc, ô tô và ngoài trời.\nTích hợp nam châm mạnh ở mặt sau, có thể gắn lên bề mặt kim loại có chứa sắt, tiện lợi khi dẫn đường, selfie/livestream hoặc xem video rảnh tay.\nTích hợp ren máy ảnh tiêu chuẩn 1/4\"-20, tương thích với tripod và gậy selfie.\nThiết kế gập gọn, nhẹ và dễ mang theo khi làm việc, du lịch hoặc sử dụng hằng ngày.",
        "id": "Cocok untuk berbagai jenis ponsel pintar.\nKompatibel dengan iPhone dan casing MagSafe asli dari Apple.\nDesain poros putar ganda, dapat disesuaikan secara fleksibel untuk berbagai sudut penggunaan.\nDapat diputar 360°, sehingga mudah beralih antara mode potret dan lanskap.\nTarik cincin berbentuk huruf D di bagian bawah untuk menjepitnya dengan cepat ke meja makan, meja baki, pegangan, dan berbagai tempat lainnya; cocok digunakan di pesawat terbang, kereta api cepat, mobil, dan di luar ruangan.\nDilengkapi magnet kuat di bagian belakang, dapat dipasang pada permukaan logam yang mengandung besi, sehingga praktis untuk navigasi, selfie/livestream, atau menonton video tanpa perlu memegang perangkat.\nDilengkapi ulir kamera standar 1/4\"-20, kompatibel dengan tripod dan tongkat selfie.\nDesainnya ringkas, ringan, dan mudah dibawa saat bekerja, bepergian, atau digunakan sehari-hari.",
        "zh": "適用於多種智慧型手機。\n相容於 iPhone 及 Apple 原廠 MagSafe 保護殼。\n採用雙旋轉軸設計，可靈活調整多種使用角度。\n可旋轉 360°，輕鬆在直式與橫式模式之間切換。\n拉動下方的 D 形環，即可快速夾在餐桌、托盤、把手等各種位置；適合在飛機、高鐵、汽車及戶外使用。\n背面內建強力磁鐵，可吸附於含鐵的金屬表面，方便進行導航、自拍／直播或免持觀看影片。\n配備 1/4\"-20 標準相機螺紋，可與三腳架及自拍桿搭配使用。\n採用可摺疊設計，輕巧且便於攜帶，無論是工作、旅遊或日常使用都十分方便。"
      },
      "reports": [],
      "gallery": [
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787380910939-6m0vh5fs0rf-K_p_du__l_ch_1.png",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787380910940-8bres3fa6dk-K_p_du_l_ch_2.png",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787381198433-sxnr80tre7-K_p_du_l_ch_3.png",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787381198434-i4mqy5shzj-K_p_du_l_ch_4.png"
      ],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "Giá Đỡ Điện Thoại Từ Tính Du Lịch Kẹp Đa Năng | VIEMAG",
        "vi": "Giá đỡ điện thoại từ tính du lịch với ngàm kẹp, hai trục xoay 360°, nam châm mặt sau và ren tripod 1/4 inch cho nhiều tình huống sử dụng.",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "Giá đỡ điện thoại từ tính du lịch với ngàm kẹp, hai trục xoay 360°, nam châm mặt sau và ren tripod 1/4 inch cho nhiều tình huống sử dụng.\tMột giá đỡ nhỏ gọn dùng trên bàn ăn, khay máy bay, tay cầm, bề mặt kim loại hoặc tripod.\n",
        "id": "",
        "zh": ""
      },
      "accessories": {
        "en": [
          "Magnetic Plate"
        ],
        "vi": [
          "Tấm từ tính"
        ],
        "id": [
          "Pelat Magnetik"
        ],
        "zh": [
          "磁性板"
        ]
      },
      "article": {
        "en": "aaa",
        "vi": "aaa",
        "id": "aaa",
        "zh": "aaa"
      },
      "faqs": [
        "no-magnet"
      ],
      "related": [
        "D01",
        "D02"
      ],
      "img": "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787379873107-cfjbo84epfh-K_p_du_l_ch.png"
    },
    {
      "sku": "PQ02",
      "slug": "pq02",
      "status": "published",
      "category": "portable",
      "subCategory": "travel",
      "art": "fold",
      "qi": "testing",
      "qiId": null,
      "watt": "15W",
      "mount": [
        "desktop"
      ],
      "price": 52.9,
      "rating": null,
      "reviews": 0,
      "badge": "new",
      "name": {
        "en": "Compact Folding Tripod Magnetic Phone Mount with Carabiner Hook | VIEMAG",
        "vi": "Giá Đỡ Điện Thoại Từ Tính Tripod Gập Gọn Kèm Móc Carabiner | VIEMAG",
        "id": "Dudukan Ponsel Magnetik dengan Tripod yang Dapat Dilipat, Dilengkapi dengan Karabiner | VIEMAG",
        "zh": "可摺疊三腳架式磁吸手機支架，附登山扣 | VIEMAG"
      },
      "claim": {
        "en": "Compatible with MagSafe-enabled phones and cases.\nGreat for podcasts, taking selfies, and creating content.\nCarabiner design—convenient to carry with you.\nMagnetic accessory holders on both sides, allowing for flexible attachment of additional accessories.\nCompact, foldable design—easy to store and carry.",
        "vi": "Tương thích với các điện thoại và ốp lưng hỗ trợ MagSafe.\nRất phù hợp để nghe podcast, chụp ảnh tự sướng và sáng tạo nội dung.\nThiết kế móc carabiner — rất tiện lợi để mang theo bên mình.\nCác giá đỡ phụ kiện từ tính ở cả hai bên, cho phép gắn thêm các phụ kiện khác một cách linh hoạt.\nThiết kế nhỏ gọn, có thể gập lại — dễ dàng cất giữ và mang theo.",
        "id": "Kompatibel dengan ponsel dan casing yang mendukung MagSafe.\nSangat cocok untuk podcast, berfoto selfie, dan membuat konten.\nDesain karabiner—praktis untuk dibawa kemana-mana.\nTempat aksesori magnetik di kedua sisi, sehingga memungkinkan pemasangan aksesori tambahan secara fleksibel.\nDesain ringkas dan dapat dilipat—mudah disimpan dan dibawa.",
        "zh": "相容於支援 MagSafe 的手機及手機殼。\n非常適合製作播客、拍攝自拍照以及創作內容。\n登山扣設計——方便隨身攜帶。\n兩側均設有磁吸式配件支架，可靈活安裝其他配件。\n輕巧、可摺疊的設計——收納與攜帶皆十分方便。"
      },
      "reports": [],
      "gallery": [
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787391880530-aky2hp439c-Gi______i_n_Tho_i_T__T_nh_Tripod_G_p_G_n_K_m_M_c_Carabiner_1.png",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787391880532-pp2hu4kc49-Gi______i_n_Tho_i_T__T_nh_Tripod_G_p_G_n_K_m_M_c_Carabiner_2.png",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787391880532-5uoxxpbr3ik-Gi______i_n_Tho_i_T__T_nh_Tripod_G_p_G_n_K_m_M_c_Carabiner_3.png"
      ],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "accessories": {
        "en": [
          "Toiletries set × 1",
          "Metal ring × 1"
        ],
        "vi": [
          "Bộ vệ sinh × 1",
          "Vòng kim loại × 1"
        ],
        "id": [
          "Set perlengkapan mandi × 1",
          "Cincin logam × 1"
        ],
        "zh": [
          "衛生套組 × 1",
          "金屬圈 × 1"
        ]
      },
      "img": "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787381998941-gmpiox4ht3r-Gi______i_n_Tho_i_T__T_nh_Tripod_G_p_G_n_K_m_M_c_Carabiner.png"
    },
    {
      "sku": "S01",
      "slug": "s01",
      "status": "future",
      "category": "studio",
      "subCategory": "creator",
      "art": "tripod",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [],
      "price": null,
      "rating": null,
      "reviews": 0,
      "badge": "soon",
      "name": {
        "en": "VIEMAG Magnetic Tripod Adapter",
        "vi": "Ngàm chân máy nam châm VIEMAG",
        "id": "Adaptor Tripod Magnetik VIEMAG",
        "zh": "VIEMAG 磁吸腳架轉接座"
      },
      "claim": {
        "en": "One magnetic head connects your phone to any 1/4\" tripod — coming soon.",
        "vi": "Một ngàm nam châm nối điện thoại với mọi chân máy 1/4\" — sắp ra mắt.",
        "id": "Satu kepala magnetik menghubungkan ponsel ke tripod 1/4\" mana pun — segera hadir.",
        "zh": "一顆磁吸頭，接上任何 1/4\" 腳架，即將推出。"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "sku": "T3",
      "slug": "t3",
      "status": "future",
      "category": "portable",
      "subCategory": null,
      "art": "tripod",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [
        "magnetic",
        "desktop"
      ],
      "price": null,
      "rating": null,
      "reviews": 0,
      "badge": "new",
      "name": {
        "en": "Foldable Mini Tripod Magnetic Phone Stand with Carabiner Hook | VIEMAG",
        "vi": "Giá Đỡ Điện Thoại Từ Tính Tripod Mini Gập Gọn Kèm Móc Carabiner | VIEMAG",
        "id": "Dudukan Ponsel Magnetik Tripod Mini Lipat dengan Kait Carabiner | VIEMAG",
        "zh": "迷你摺疊三腳架磁吸手機支架，附登山扣 | VIEMAG"
      },
      "claim": {
        "en": "Uses an N52 magnet for a secure magnetic hold.\nFully foldable frame — adjust the viewing angle freely.\nRotates 360°, easily switch between portrait and landscape.\nMini tripod design keeps desktop shots steady, no wobble.\nWorks as a phone stand, selfie stand, and shooting tripod.\nCarabiner hook design clips onto bags and straps — compact and easy to carry.\nIncludes a magnetic plate, so non-MagSafe phones can use it too.",
        "vi": "Nam châm N52, hút chắc điện thoại.\nKhung gập toàn phần, tự do điều chỉnh góc nhìn.\nXoay 360°, dễ dàng chuyển dọc/ngang.\nThiết kế tripod mini, đặt bàn ổn định không rung.\nDùng được như giá đỡ điện thoại, gậy tự sướng và tripod quay phim.\nThiết kế móc carabiner, dễ móc vào túi/dây đeo, gọn nhẹ dễ mang.\nKèm tấm sắt từ tính, điện thoại không hỗ trợ MagSafe vẫn dùng được.",
        "id": "Magnet N52, cengkeraman magnetik kuat untuk ponsel.\nRangka lipat penuh, sesuaikan sudut pandang bebas.\nBerputar 360°, mudah beralih potret/lanskap.\nDesain tripod mini, pengambilan gambar di meja stabil tanpa goyang.\nBisa jadi dudukan ponsel, tongkat selfie, dan tripod syuting.\nDesain kait carabiner, mudah dikaitkan ke tas/tali, ringkas dan mudah dibawa.\nTermasuk pelat magnetik, ponsel non-MagSafe pun bisa pakai.",
        "zh": "採用 N52 磁鐵，穩固吸附手機。\n全折疊結構，自由調整觀看角度。\n360 度旋轉，輕鬆切換直向與橫向。\n迷你三腳架設計，桌面拍攝穩定不晃動。\n可作為手機支架、自拍支架及拍攝三腳架。\n掛勾式設計，方便掛包包與背帶，輕巧便攜好收納。\n隨附引磁片，不支援 MagSafe 的裝置也能使用。"
      },
      "reports": [],
      "gallery": [
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787909394515-0yquq5jenppj-1.jpg",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787909394515-jfrqv4rpw8b-2.jpg",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787909394515-p8jtzzhtg8g-3.jpg",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787909394515-47w1lhl92wg-4.jpg",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787909394515-4n81zri07bl-5.jpg",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787909394516-vym0qaf50e-6.jpg",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787909394516-28bfbzcmeli-7.jpg",
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787909394516-xkqzukipsqm-8.jpg"
      ],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "accessories": {
        "en": [
          "Adhesive Magnetic Ring"
        ],
        "vi": [
          "Vòng từ tính dạng dán"
        ],
        "id": [
          "Cincin Magnetik Tempel"
        ],
        "zh": [
          "黏貼式磁吸環"
        ]
      },
      "article": {
        "en": "## A pocket tripod that doubles as a phone stand\nUnfold it on a desk for hands-free video calls and content shoots, or clip the carabiner hook to a bag strap for the walk over.\n\n## N52 magnet, mini tripod stance\nThe magnetic face holds compatible phones centered and steady, while the three-leg tripod base keeps the angle fixed — no leaning against a cup or laptop lid.\n\n- Fully foldable frame, rotates 360° for portrait or landscape\n- Carabiner hook clips onto bags and straps for the walk over\n- Ships with a magnetic plate, so non-MagSafe phones work too",
        "vi": "## Tripod bỏ túi, kiêm luôn giá đỡ điện thoại\nMở ra trên bàn khi cần gọi video hoặc quay nội dung rảnh tay, gập lại và móc carabiner vào dây balo khi di chuyển.\n\n## Nam châm N52, dáng đứng tripod mini\nMặt nam châm giữ điện thoại tương thích đúng tâm và chắc chắn, ba chân tripod giữ góc cố định — không cần tựa vào ly hay nắp laptop.\n\n- Khung gập toàn phần, xoay 360° cho cả dọc lẫn ngang\n- Móc carabiner gắn vào túi/dây đeo khi di chuyển\n- Kèm tấm từ tính, điện thoại không hỗ trợ MagSafe vẫn dùng được",
        "id": "## Tripod saku yang juga jadi dudukan ponsel\nBuka di meja saat butuh panggilan video atau merekam konten tanpa pegang tangan, lipat dan kaitkan carabiner ke tali tas saat bepergian.\n\n## Magnet N52, posisi tripod mini\nPermukaan magnetik menahan ponsel kompatibel tetap di tengah dan stabil, tiga kaki tripod menjaga sudut tetap — tanpa perlu disandarkan ke gelas atau tutup laptop.\n\n- Rangka lipat penuh, berputar 360° untuk potret maupun lanskap\n- Kait carabiner terpasang ke tas/tali saat bepergian\n- Termasuk pelat magnetik, ponsel non-MagSafe pun bisa pakai",
        "zh": "## 口袋三腳架，也是手機支架\n放在桌上即可免持視訊或拍攝內容，收合後用登山扣掛在背包背帶上就能出門。\n\n## N52 磁吸，迷你三腳架站姿\n磁吸面讓相容手機穩固置中，三腳底座維持角度固定，不必再倚靠杯子或筆電上蓋。\n\n- 全折疊機身，可 360° 旋轉切換直向橫向\n- 登山扣可掛在包包或背帶上方便攜帶\n- 隨附引磁片，不支援 MagSafe 的手機也能使用"
      },
      "img": "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787909508461-ncwjllzoyh-___.jpg"
    },
    {
      "sku": "V01",
      "slug": "v01",
      "status": "published",
      "category": "vehicle",
      "subCategory": "mounts",
      "art": "vent",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [
        "vent"
      ],
      "price": 15.9,
      "rating": null,
      "reviews": 0,
      "badge": null,
      "name": {
        "en": "360° Magnetic Phone Mount for Air Vents | VIEMAG",
        "vi": "Giá Đỡ Điện Thoại Từ Tính Gắn Cửa Gió 360° | VIEMAG",
        "id": "Dudukan Ponsel Magnetik yang Dapat Dipasang di Ventilasi 360° | VIEMAG",
        "zh": "360° 磁吸式車門通風口手機支架 | VIEMAG"
      },
      "claim": {
        "en": "360° rotation — flexibly switch between portrait and landscape orientations.\n17 mm ball joint — easily attaches to compatible phone mounts.\nProtective rubber layer — minimizes scratches in contact areas.",
        "vi": "Xoay 360° — linh hoạt chuyển góc nhìn dọc hoặc ngang.\nKhớp bi 17 mm — dễ kết hợp với các đầu giữ điện thoại tương thích.\nLớp cao su bảo vệ — hạn chế trầy xước tại vùng tiếp xúc.",
        "id": "Berputar 360° — fleksibel untuk mengubah sudut pandang secara vertikal atau horizontal.\nSendi bola 17 mm — mudah dipasangkan dengan dudukan ponsel yang kompatibel.\nLapisan karet pelindung — mengurangi goresan pada area yang bersentuhan.",
        "zh": "360°旋轉 — 可靈活切換縱向或橫向視角。\n17 公釐球形關節 — 輕鬆搭配相容的手機固定座。\n保護性橡膠層——可減少接觸處的刮痕。"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "Giá đỡ điện thoại từ tính gắn cửa gió, xoay 360° và dùng chuẩn khớp bi 17 mm, giúp điều chỉnh góc nhìn linh hoạt khi lái xe.",
        "id": "",
        "zh": ""
      },
      "accessories": {
        "en": [
          "Alcohol-soaked wipes",
          "Magnetic Support Ring"
        ],
        "vi": [
          "Khăn tẩm cồn",
          "Vòng kim loại dán hỗ trợ từ tính"
        ],
        "id": [
          "Kain yang dibasahi alkohol",
          "Cincin logam tempel dengan dukungan magnetik"
        ],
        "zh": [
          "酒精濕巾",
          "磁性支撐貼片金屬環"
        ]
      },
      "img": "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787374463701-ddmx7zval24-K_p_c_a_gi___i_u_h_a.png"
    },
    {
      "sku": "V02",
      "slug": "v02",
      "status": "published",
      "category": "vehicle",
      "subCategory": "mounts",
      "art": "dash",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [
        "dashboard"
      ],
      "price": 19.9,
      "rating": null,
      "reviews": 0,
      "badge": "bestseller",
      "name": {
        "en": "VIEMAG Dashboard Magnetic Mount",
        "vi": "Giá đỡ nam châm táp-lô VIEMAG",
        "id": "Dudukan Magnetik Dasbor VIEMAG",
        "zh": "VIEMAG 儀表板磁吸支架"
      },
      "claim": {
        "en": "All-day navigation on the dash that stays put under hard braking.",
        "vi": "Dẫn đường cả ngày trên táp-lô, phanh gấp vẫn đứng yên.",
        "id": "Navigasi seharian di dasbor yang tetap diam saat mengerem mendadak.",
        "zh": "儀表板全日導航，急煞依然穩固。"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "sku": "V03",
      "slug": "v03",
      "status": "published",
      "category": "vehicle",
      "subCategory": "mounts",
      "art": "tape",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [
        "tape"
      ],
      "price": 17.9,
      "rating": null,
      "reviews": 0,
      "badge": null,
      "name": {
        "en": "N52 Magnetic Phone Mount with Vacuum Suction and 360° Rotation | VIEMAG",
        "vi": "Giá Đỡ Điện Thoại Từ Tính N52 Hút Chân Không Xoay 360° | VIEMAG",
        "id": "Dudukan Ponsel Magnetik N52 dengan Hisap Vakum dan Dapat Berputar 360° | VIEMAG",
        "zh": "N52 磁吸式 360° 旋轉 真空吸盤手機支架 | VIEMAG"
      },
      "claim": {
        "en": "The soft TPU base, combined with a suction mechanism, allows for flexible placement of the phone on a suitable surface.",
        "vi": "Đế TPU mềm kết hợp cơ cấu hút giúp tạo điểm đặt điện thoại linh hoạt trên bề mặt phù hợp.",
        "id": "Basis TPU yang lembut dipadukan dengan mekanisme hisap memungkinkan penempatan ponsel secara fleksibel pada permukaan yang sesuai.",
        "zh": "柔軟的 TPU 底座結合吸附結構，可讓手機在合適的表面上靈活定位。"
      },
      "reports": [],
      "gallery": [
        "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787384270413-k24pewvj84s-___A1_ZF162_N52________.jpeg"
      ],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "img": "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787383375551-8rc6siqagt8-A1.png"
    },
    {
      "sku": "V04",
      "slug": "v04",
      "status": "published",
      "category": "vehicle",
      "subCategory": "mounts",
      "art": "suction",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [
        "suction"
      ],
      "price": 22.9,
      "rating": null,
      "reviews": 0,
      "badge": null,
      "name": {
        "en": "VIEMAG Suction Long-Arm Mount",
        "vi": "Giá đỡ tay dài đế hút chân không VIEMAG",
        "id": "Dudukan Lengan Panjang Vakum VIEMAG",
        "zh": "VIEMAG 吸盤長臂磁吸支架"
      },
      "claim": {
        "en": "A long arm for any viewing angle, vacuum base grips glass and dash.",
        "vi": "Tay đòn dài chỉnh mọi góc nhìn, đế hút bám chắc kính và táp-lô.",
        "id": "Lengan panjang untuk segala sudut pandang, dasar vakum mencengkeram kaca dan dasbor.",
        "zh": "長臂調整任何視角，吸盤緊咬玻璃與儀表板。"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "sku": "V05",
      "slug": "v05",
      "status": "published",
      "category": "vehicle",
      "subCategory": "mounts",
      "art": "",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [],
      "price": 19.9,
      "rating": null,
      "reviews": 0,
      "badge": null,
      "name": {
        "en": "Slim Suction Cup Magsafe Mount",
        "vi": "Giá đỡ Magsafe dạng cốc hút mỏng",
        "id": "Dudukan Magsafe Berbentuk Cangkir Hisap yang Ramping",
        "zh": "超薄吸盤式 MagSafe 支架"
      },
      "claim": {
        "en": "The Thinnest and Lightest MagSafe Suction Cup Stand",
        "vi": "Giá đỡ Magsafe bằng miếng hút mỏng và nhẹ nhất",
        "id": "Dudukan Magsafe dengan pengisap yang paling tipis dan ringan",
        "zh": "最輕薄的吸盤 Magsafe 支架"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "img": "https://zqmpjenlpzmeozoufvzy.supabase.co/storage/v1/object/public/viemag-media/products/1787385364682-1n14m9fxwpe-S4.png"
    },
    {
      "sku": "V06",
      "slug": "v06",
      "status": "published",
      "category": "vehicle",
      "subCategory": "mounts",
      "art": "clip",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [
        "screen"
      ],
      "price": 24.9,
      "rating": null,
      "reviews": 0,
      "badge": "new",
      "name": {
        "en": "VIEMAG Screen-Edge Magnetic Mount",
        "vi": "Giá kẹp màn hình trung tâm VIEMAG",
        "id": "Dudukan Magnetik Tepi Layar VIEMAG",
        "zh": "VIEMAG 螢幕邊磁吸支架"
      },
      "claim": {
        "en": "Clips to the center screen edge — no vents blocked, no adhesive.",
        "vi": "Kẹp cạnh màn hình trung tâm, không che cửa gió, không dán keo.",
        "id": "Menjepit tepi layar tengah — tanpa menutup kisi AC, tanpa perekat.",
        "zh": "夾在中控螢幕邊，不擋出風口、不用貼膠。"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "sku": "V07",
      "slug": "v07",
      "status": "published",
      "category": "vehicle",
      "subCategory": "mounts",
      "art": "pro",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [
        "vent",
        "dashboard"
      ],
      "price": 24.9,
      "rating": null,
      "reviews": 0,
      "badge": "bestseller",
      "name": {
        "en": "VIEMAG Pro Anti-Vibration Strong Mount",
        "vi": "Giá đỡ chống rung lực hút mạnh VIEMAG Pro",
        "id": "Dudukan Kuat Anti-Getar VIEMAG Pro",
        "zh": "VIEMAG Pro 強磁耐震支架"
      },
      "claim": {
        "en": "N52 magnets and an anti-vibration build — the proof piece of the lineup.",
        "vi": "Nam châm N52 và kết cấu chống rung — bằng chứng chất lượng của cả dòng sản phẩm.",
        "id": "Magnet N52 dan konstruksi anti-getar — bukti kualitas seluruh lini.",
        "zh": "N52 強磁與耐震結構，整條產品線的品質證據款。"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "sku": "V08",
      "slug": "v08",
      "status": "published",
      "category": "vehicle",
      "subCategory": "mounts",
      "art": "suction",
      "qi": "none",
      "qiId": null,
      "watt": null,
      "mount": [
        "dashboard",
        "suction",
        "screen",
        "desktop"
      ],
      "price": 24.9,
      "rating": null,
      "reviews": 0,
      "badge": "bestseller",
      "name": {
        "en": "Extended Aluminum Alloy Universal Magnetic Mount",
        "vi": "Giá Đỡ Từ Tính Đa Năng Dài Hơn, Khung Hợp Kim Nhôm",
        "id": "Dudukan Magnetik Serbaguna Aluminium Alloy Versi Panjang",
        "zh": "鋁合金加長型萬用磁吸支架"
      },
      "claim": {
        "en": "PU gel suction cup, aluminum alloy build, foldable extendable magnetic mount — a dependable companion for driving and everyday recording.",
        "vi": "Đế hút PU gel, chất liệu hợp kim nhôm, giá đỡ nam châm gập gọn kéo dài — người bạn đồng hành đáng tin cậy cho mọi hành trình và khoảnh khắc.",
        "id": "Cangkir hisap gel PU, bahan aluminium alloy, dudukan magnetik lipat yang bisa dipanjangkan — teman yang andal untuk berkendara dan merekam keseharian.",
        "zh": "PU 凝膠吸盤，鋁合金材質，可收摺加長型磁吸支架，行車駕駛、生活紀錄的好夥伴。"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "img": "assets/products/VB001DSH1_BK.png"
    },
    {
      "sku": "VQ09",
      "slug": "vq09",
      "status": "published",
      "category": "vehicle",
      "subCategory": "charging-mounts",
      "art": "carcharge",
      "qi": "compatible",
      "qiId": null,
      "watt": "15W",
      "mount": [
        "vent"
      ],
      "price": 35.9,
      "rating": null,
      "reviews": 0,
      "badge": null,
      "name": {
        "en": "VIEMAG Vent 15W Wireless Charging Mount",
        "vi": "Giá sạc cửa gió 15W VIEMAG",
        "id": "Dudukan Pengisi Kisi AC 15W VIEMAG",
        "zh": "VIEMAG 出風口 15W 車充支架"
      },
      "claim": {
        "en": "Dock and charge at 15W, built to the Qi2 standard, cooled by the vent airflow.",
        "vi": "Gắn là sạc 15W, thiết kế theo chuẩn Qi2, gió điều hoà hỗ trợ tản nhiệt.",
        "id": "Tempel dan isi 15W, dibuat sesuai standar Qi2, didinginkan aliran udara kisi AC.",
        "zh": "一吸即充 15W，依 Qi2 標準設計，出風口氣流輔助散熱。"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "sku": "VQ10",
      "slug": "vq10",
      "status": "published",
      "category": "vehicle",
      "subCategory": "charging-mounts",
      "art": "dashcharge",
      "qi": "compatible",
      "qiId": null,
      "watt": "15W",
      "mount": [
        "dashboard"
      ],
      "price": 39.9,
      "rating": null,
      "reviews": 0,
      "badge": "bestseller",
      "name": {
        "en": "VIEMAG Dashboard 15W Wireless Charging Mount",
        "vi": "Giá sạc táp-lô 15W VIEMAG",
        "id": "Dudukan Pengisi Dasbor 15W VIEMAG",
        "zh": "VIEMAG 儀表板 15W 車充支架"
      },
      "claim": {
        "en": "The workhorse: all-day navigation with 15W charging that keeps its cool.",
        "vi": "Chủ lực của dòng sạc xe: dẫn đường cả ngày, sạc 15W không quá nóng.",
        "id": "Andalan: navigasi seharian dengan pengisian 15W yang tetap adem.",
        "zh": "車充主力款：全日導航，15W 充電不過熱。"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "sku": "VQ11",
      "slug": "vq11",
      "status": "published",
      "category": "vehicle",
      "subCategory": "charging-mounts",
      "art": "fancharge",
      "qi": "testing",
      "qiId": null,
      "watt": "25W",
      "mount": [
        "vent",
        "dashboard"
      ],
      "price": 55.9,
      "rating": null,
      "reviews": 0,
      "badge": "new",
      "name": {
        "en": "VIEMAG 25W Active-Cooling Charging Mount",
        "vi": "Giá sạc 25W tản nhiệt chủ động VIEMAG",
        "id": "Dudukan Pengisi Pendingin Aktif 25W VIEMAG",
        "zh": "VIEMAG 25W 主動散熱車充支架"
      },
      "claim": {
        "en": "25W fast charging built to Qi2.2 with an active cooling fan — the flagship.",
        "vi": "Sạc nhanh 25W theo chuẩn Qi2.2 với quạt tản nhiệt chủ động — mẫu đầu bảng.",
        "id": "Pengisian cepat 25W dibuat sesuai Qi2.2 dengan kipas pendingin aktif — model unggulan.",
        "zh": "依 Qi2.2 標準設計的 25W 快充＋主動散熱風扇，旗艦款。"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    },
    {
      "sku": "VQ12",
      "slug": "vq12",
      "status": "published",
      "category": "vehicle",
      "subCategory": "charging-mounts",
      "art": "suctioncharge",
      "qi": "compatible",
      "qiId": null,
      "watt": "15W",
      "mount": [
        "suction"
      ],
      "price": 45.9,
      "rating": null,
      "reviews": 0,
      "badge": null,
      "name": {
        "en": "VIEMAG Long-Arm Adjustable Charging Mount",
        "vi": "Giá sạc tay dài điều chỉnh VIEMAG",
        "id": "Dudukan Pengisi Lengan Panjang VIEMAG",
        "zh": "VIEMAG 長臂可調車充支架"
      },
      "claim": {
        "en": "A long adjustable arm for deep dashboards — hold and charge in one.",
        "vi": "Tay đòn dài cho xe có táp-lô sâu, vừa giữ vừa sạc.",
        "id": "Lengan panjang yang bisa disetel untuk dasbor dalam — menahan dan mengisi sekaligus.",
        "zh": "深儀表板車型的長臂解法，支撐與充電一次到位。"
      },
      "reports": [],
      "gallery": [],
      "warranty": 12,
      "exchange": 14,
      "seoTitle": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      },
      "seoDesc": {
        "en": "",
        "vi": "",
        "id": "",
        "zh": ""
      }
    }
  ],
  "tests": [
    {
      "id": "vibration",
      "icon": "wave",
      "name": {
        "vi": "Kiểm tra rung xóc",
        "en": "Vibration Testing",
        "id": "Uji Getaran",
        "zh": "震動測試"
      },
      "desc": {
        "vi": "Mô phỏng mặt đường xấu và phanh gấp trước khi xuất xưởng.",
        "en": "Simulates rough roads and hard braking before any unit ships.",
        "id": "Mensimulasikan jalan rusak dan pengereman mendadak sebelum unit dikirim.",
        "zh": "出貨前模擬爛路與急煞情境。"
      }
    },
    {
      "id": "thermal",
      "icon": "thermo",
      "name": {
        "vi": "Kiểm tra tăng nhiệt",
        "en": "Thermal-Rise Testing",
        "id": "Uji Kenaikan Suhu",
        "zh": "溫升測試"
      },
      "desc": {
        "vi": "Theo dõi nhiệt độ suốt chu kỳ sạc — bảo vệ điện thoại của bạn khi sạc.",
        "en": "Charge-cycle temperature profiling — protects your phone while charging.",
        "id": "Pemantauan suhu sepanjang siklus pengisian — melindungi ponsel Anda saat mengisi daya.",
        "zh": "全充電週期溫度監控，充電時更保護您的手機。"
      }
    },
    {
      "id": "magnetic",
      "icon": "magnet",
      "name": {
        "vi": "Kiểm tra lực hút",
        "en": "Magnetic Force Testing",
        "id": "Uji Gaya Magnet",
        "zh": "磁力測試"
      },
      "desc": {
        "vi": "Đo lực giữ theo mọi hướng, kể cả khi dùng ốp lưng.",
        "en": "Holding force measured in every direction, case-on included.",
        "id": "Gaya tahan diukur ke segala arah, termasuk saat memakai casing.",
        "zh": "各方向吸持力實測，含裝殼狀態。"
      }
    },
    {
      "id": "lifecycle",
      "icon": "cycle",
      "name": {
        "vi": "Tuổi thọ hút – nhả",
        "en": "Attach-Release Lifecycle",
        "id": "Uji Umur Tempel–Lepas",
        "zh": "吸合壽命測試"
      },
      "desc": {
        "vi": "Hàng nghìn chu kỳ gắn – tháo và kiểm tra khớp xoay.",
        "en": "Thousands of dock-release cycles plus hinge endurance.",
        "id": "Ribuan siklus tempel–lepas plus ketahanan engsel.",
        "zh": "數千次吸合循環與球頭鉸鏈耐久。"
      }
    }
  ],
  "reports": [],
  "insights": [],
  "faqs": [
    {
      "id": "doa",
      "cat": "",
      "q": {
        "en": "How do I exchange a defective item on arrival?",
        "vi": "Hàng lỗi khi nhận được đổi mới thế nào?",
        "id": "Bagaimana menukar barang cacat saat tiba?",
        "zh": "到貨瑕疵如何換新？"
      },
      "a": {
        "en": "Within 14 days of delivery, send photos or a short video of the defect to support — we replace, not repair.",
        "vi": "Trong 14 ngày kể từ khi nhận hàng, gửi ảnh hoặc video sản phẩm lỗi cho CSKH — chúng tôi đổi mới, không sửa chữa.",
        "id": "Dalam 14 hari sejak barang tiba, kirim foto atau video singkat cacatnya ke dukungan — kami mengganti, bukan memperbaiki.",
        "zh": "到貨 14 天內提供照片或影片給客服，直接換新品、不維修。"
      }
    },
    {
      "id": "heat",
      "cat": "",
      "q": {
        "en": "Is it normal for the phone to get warm while charging?",
        "vi": "Sạc không dây bị ấm máy có bình thường không?",
        "id": "Apakah wajar ponsel menghangat saat mengisi?",
        "zh": "無線充電時發熱正常嗎？"
      },
      "a": {
        "en": "Mild warmth is normal. Every VIEMAG charger passes thermal-rise testing; if it gets unusually hot, remove overly thick cases and contact support.",
        "vi": "Ấm nhẹ là bình thường. Sản phẩm VIEMAG đều qua kiểm tra tăng nhiệt; nếu máy nóng bất thường, hãy tháo ốp quá dày và liên hệ CSKH.",
        "id": "Hangat ringan itu wajar. Setiap pengisi VIEMAG lolos uji kenaikan suhu; jika terlalu panas, lepaskan casing yang terlalu tebal dan hubungi dukungan.",
        "zh": "微溫屬正常。VIEMAG 充電產品皆通過溫升測試；若異常發燙，請先移除過厚手機殼並聯絡客服。"
      }
    },
    {
      "id": "no-magnet",
      "cat": "",
      "q": {
        "en": "My phone has no built-in magnets. Can I still use VIEMAG?",
        "vi": "Điện thoại của tôi không có nam châm, dùng được không?",
        "id": "Ponsel saya tidak punya magnet. Masih bisa pakai VIEMAG?",
        "zh": "我的手機沒有磁吸功能，可以用嗎？"
      },
      "a": {
        "en": "Yes. Add a VIEMAG adapter ring or magnetic case from the accessories line and any phone works across the whole system.",
        "vi": "Được. Chỉ cần dán vòng chuyển đổi VIEMAG hoặc dùng ốp lưng nam châm trong bộ phụ kiện, mọi điện thoại đều gắn được lên toàn hệ sản phẩm.",
        "id": "Bisa. Tambahkan cincin adaptor VIEMAG atau casing magnetik dari lini aksesori, dan ponsel apa pun bekerja di seluruh sistem.",
        "zh": "可以。貼上 VIEMAG 轉接環或使用磁吸手機殼，任何手機都能使用整個系統。"
      }
    },
    {
      "id": "tape",
      "cat": "",
      "q": {
        "en": "Can the 3M adhesive pad be reused?",
        "vi": "Miếng dán 3M có dùng lại được không?",
        "id": "Apakah bantalan perekat 3M bisa dipakai ulang?",
        "zh": "3M 貼片可以重複使用嗎？"
      },
      "a": {
        "en": "3M adhesive bonds strongest on first application. Use the spare pad included in the box when relocating the mount.",
        "vi": "Keo 3M dán chắc nhất ở lần đầu. Khi cần dời vị trí, hãy dùng miếng keo thay thế trong hộp để đảm bảo độ bám.",
        "id": "Perekat 3M paling kuat pada pemasangan pertama. Gunakan bantalan cadangan dalam kotak saat memindahkan dudukan.",
        "zh": "3M 背膠首次黏貼最牢，移位時請使用盒內備用貼片以確保黏著力。"
      }
    },
    {
      "id": "vent",
      "cat": "",
      "q": {
        "en": "Which car vents are not suitable for vent mounts?",
        "vi": "Loại cửa gió nào không phù hợp với giá đỡ cửa gió?",
        "id": "Kisi AC mobil seperti apa yang tidak cocok untuk dudukan kisi?",
        "zh": "哪些出風口不適合安裝出風口支架？"
      },
      "a": {
        "en": "Round rotating vents, very thin blades or hidden electronic vents may not hold firmly. Choose the dashboard or 3M tape version instead.",
        "vi": "Cửa gió tròn xoay, lá gió quá mảnh hoặc cửa gió điện tử ẩn có thể không giữ chắc. Trường hợp đó nên chọn bản táp-lô hoặc bản dán 3M.",
        "id": "Kisi bulat berputar, bilah sangat tipis, atau kisi elektronik tersembunyi mungkin tidak menahan kuat. Pilih versi dasbor atau perekat 3M.",
        "zh": "圓形旋轉式、葉片過細或隱藏式電子出風口可能不穩，建議改用儀表板款或 3M 貼片款。"
      }
    },
    {
      "id": "warranty",
      "cat": "",
      "q": {
        "en": "What does the 12-month warranty cover?",
        "vi": "Bảo hành 12 tháng gồm những gì?",
        "id": "Apa saja yang dicakup garansi 12 bulan?",
        "zh": "12 個月保固涵蓋哪些問題？"
      },
      "a": {
        "en": "Material and manufacturing defects under normal use: abnormal magnet weakening, loose joints, charging failures. Drop or impact damage is not covered.",
        "vi": "Lỗi vật liệu và lỗi sản xuất trong sử dụng bình thường: nam châm suy yếu bất thường, khớp lỏng, lỗi sạc. Hư hại do rơi vỡ, va đập không thuộc phạm vi bảo hành.",
        "id": "Cacat material dan produksi dalam pemakaian normal: magnet melemah tak wajar, sendi kendur, gagal mengisi. Kerusakan akibat jatuh atau benturan tidak dicakup.",
        "zh": "正常使用下的材料與製造瑕疵：磁力異常衰減、關節鬆動、充電故障。摔落撞擊等人為損壞不在範圍內。"
      }
    },
    {
      "id": "why-ring",
      "cat": "",
      "q": {
        "en": "Why do I need a magnetic case or adapter ring?",
        "vi": "Vì sao cần ốp lưng nam châm hoặc vòng chuyển đổi?",
        "id": "Kenapa saya perlu casing magnetik atau cincin adaptor?",
        "zh": "為什麼需要磁吸手機殼或轉接環？"
      },
      "a": {
        "en": "Magnetic holding needs a correctly centered ring. A case or adapter ring guarantees alignment for a firm hold and efficient charging.",
        "vi": "Lực hút cần vòng nam châm định vị đúng tâm. Ốp hoặc vòng chuyển đổi đảm bảo vị trí chuẩn để giữ chắc và sạc hiệu quả.",
        "id": "Penahanan magnetik butuh cincin yang terpusat tepat. Casing atau cincin adaptor menjamin keselarasan untuk cengkeraman kuat dan pengisian efisien.",
        "zh": "磁吸需要正確對位的磁環，手機殼或轉接環能確保吸持穩固與充電效率。"
      }
    }
  ],
  "config": {
    "shopeeUrl": "#",
    "warrantyMonths": 12,
    "exchangeDays": 14
  }
};
