/* ============================================================
   VIEMAG — Mock Data Layer
   Field structure mirrors the Notion databases (Products /
   Categories / Scenarios / FAQ). Swap this file for a Notion
   API export later — front-end rendering reads only from DB.*
   Mock products are placeholders to be replaced with final SKUs.
   NOTE: qi values are 'none' | 'compatible' | 'testing' | 'certified'.
   Only 'certified' may ever render a certified badge (none are, today).
   ============================================================ */
window.DB = {

  /* ---- Categories (Notion: Categories) ---- */
  categories: [
    { id:'car-mounts', cat:'CAT-B', status:'published', sort:1, art:'dash',
      name:{ vi:'Giá đỡ nam châm ô tô', en:'Car Magnetic Mounts', zh:'車用磁吸支架' },
      desc:{ vi:'Lái xe, dẫn đường, hút chắc không rơi — dòng chủ lực của VIEMAG.',
             en:'Drive, navigate, one-hand dock. The flagship line built for daily commutes.',
             zh:'開車導航、單手取放、穩固不掉，VIEMAG 的旗艦產品線。' } },
    { id:'car-chargers', cat:'CAT-B', status:'published', sort:2, art:'carcharge',
      name:{ vi:'Giá sạc ô tô chuẩn Qi2', en:'Qi2 Car Charging Mounts', zh:'Qi2 車用充電支架' },
      desc:{ vi:'Vừa giữ chắc vừa sạc nhanh 15W–25W, kiểm soát nhiệt khi dẫn đường.',
             en:'Hold firm and fast-charge at 15W–25W with managed heat while navigating.',
             zh:'穩固支撐同時 15W–25W 快充，導航時溫度受控。' } },
    { id:'desk-travel', cat:'CAT-A', status:'published', sort:3, art:'deskcharge',
      name:{ vi:'Sạc Qi2 để bàn & du lịch', en:'Desk & Travel Qi2 Chargers', zh:'桌面/旅行 Qi2 充電器' },
      desc:{ vi:'Bàn làm việc gọn gàng, đi công tác nhẹ hành lý.',
             en:'A tidier desk at work, a lighter bag on the road.',
             zh:'工作桌面更整潔，出差行李更輕。' } },
    { id:'accessories', cat:'CAT-E', status:'published', sort:4, art:'ring',
      name:{ vi:'Phụ kiện nam châm', en:'Magnetic Accessories', zh:'磁吸擴充配件' },
      desc:{ vi:'Vòng chuyển đổi và ốp lưng giúp mọi điện thoại dùng được hệ nam châm.',
             en:'Adapter rings and cases that bring any phone into the magnetic system.',
             zh:'轉接環與手機殼，讓任何手機都能進入磁吸系統。' } },
    { id:'portable-power', cat:'CAT-C', status:'future', sort:5, art:'powerbank',
      name:{ vi:'Nguồn di động nam châm', en:'Portable Magnetic Power', zh:'隨身磁吸行動電源' },
      desc:{ vi:'Pin dự phòng hút dán sau máy — sắp ra mắt.',
             en:'Snap-on power banks for the road — coming soon.',
             zh:'吸附即充的行動電源，即將推出。' } },
    { id:'stands-display', cat:'CAT-D', status:'future', sort:6, art:'stand',
      name:{ vi:'Giá đỡ & hiển thị', en:'Stands & Display', zh:'立架影音生態' },
      desc:{ vi:'Giá đỡ bàn làm việc, đầu giường và quay video — sắp ra mắt.',
             en:'Desk, bedside and creator stands — coming soon.',
             zh:'桌面、床邊與創作立架，即將推出。' } }
  ],

  /* ---- Scenarios (Notion: Scenarios, S1–S6) ---- */
  scenarios: [
    { code:'S2', id:'driving', priority:1, status:'primary', icon:'car',
      name:{ vi:'Lái xe & Di chuyển', en:'Driving & Commute', zh:'通勤・行動' },
      desc:{ vi:'Dẫn đường ổn định, lấy – gắn một tay, không lo rơi khi phanh gấp.',
             en:'Stable navigation, one-hand dock and release, no drops under hard braking.',
             zh:'導航穩定、單手取放，急煞不掉落。' },
      combo:['VMG-B2-Dash','VMG-B2-Qi2-15W','VMG-E1-Ring'] },
    { code:'S3', id:'deskwork', priority:2, status:'secondary', icon:'desk',
      name:{ vi:'Làm việc & Văn phòng', en:'Work & Office', zh:'工作・辦公' },
      desc:{ vi:'Vừa sạc vừa họp video, bàn làm việc không dây rối.',
             en:'Charge through video calls with a cable-free desk.',
             zh:'邊充電邊視訊，桌面沒有線材糾纏。' },
      combo:['VMG-A2-Desk','VMG-A1-Qi2','VMG-E2-CaseKit'] },
    { code:'S5', id:'travel', priority:3, status:'supporting', icon:'plane',
      name:{ vi:'Công tác & Du lịch', en:'Travel & Business Trips', zh:'差旅・出差' },
      desc:{ vi:'Một củ sạc gập gọn thay cả túi dây cáp.',
             en:'One folding charger replaces a pouch full of cables.',
             zh:'一顆折疊充電器，取代一整包線材。' },
      combo:['VMG-A3-Fold','VMG-E1-Ring'] },
    { code:'S1', id:'morning', priority:4, status:'future', icon:'sun',
      name:{ vi:'Buổi sáng & Đầu giường', en:'Morning & Bedside', zh:'晨起・梳妝' },
      desc:{ vi:'Sạc qua đêm, báo thức và bắt đầu ngày mới — hệ sản phẩm đang mở rộng.',
             en:'Overnight charging and morning routines — lineup expanding.',
             zh:'夜間充電與晨間節奏，產品線擴充中。' },
      combo:[] },
    { code:'S4', id:'home', priority:5, status:'future', icon:'home',
      name:{ vi:'Ở nhà & Thư giãn', en:'Home & Leisure', zh:'居家・休憩' },
      desc:{ vi:'Xem phim, vào bếp, cả nhà dùng chung một hệ nam châm.',
             en:'Movies, kitchen, family charging — one magnetic system shared at home.',
             zh:'追劇、下廚，全家共用同一套磁吸系統。' },
      combo:[] },
    { code:'S6', id:'creator', priority:6, status:'future', icon:'camera',
      name:{ vi:'Ngoài trời & Sáng tạo', en:'Outdoor & Creator', zh:'戶外・創作' },
      desc:{ vi:'Vlog, quay chụp, chân máy chuyển đổi — hệ mở rộng cho nhà sáng tạo.',
             en:'Vlogging, tripods and creator modules — the expandable system.',
             zh:'Vlog 拍攝、腳架轉接，創作者的擴充系統。' },
      combo:[] }
  ],

  /* ---- Personas (whitepaper 4.4) ---- */
  personas: [
    { id:'commuter', icon:'car', age:'25–40',
      name:{ vi:'Người đi làm yêu công nghệ', en:'Tech Commuter', zh:'科技通勤族' },
      desc:{ vi:'Mỗi lần đổi bối cảnh là một lần tháo – gắn. Nam châm giúp tiết kiệm 3 giây mỗi lần, cả ngày là hàng chục lần.',
             en:'Every scene change means re-docking the phone. Magnets give those 3 seconds back, dozens of times a day.',
             zh:'每換一個場景就要重新固定手機，磁吸把每次 3 秒省回來。' },
      picks:['car-mounts','car-chargers'] },
    { id:'homeoffice', icon:'desk', age:'30–50',
      name:{ vi:'Chuyên gia làm việc tại nhà', en:'Home-Office Professional', zh:'居家辦公專業者' },
      desc:{ vi:'Bàn làm việc gọn là một phần của năng suất. Sạc đứng, họp video, không dây rối.',
             en:'A tidy desk is part of productivity. Upright charging through every call, zero cable mess.',
             zh:'桌面整潔是生產力的一部分，立式充電、視訊零線材。' },
      picks:['desk-travel','stands-display'] },
    { id:'traveler', icon:'plane', age:'35–55',
      name:{ vi:'Doanh nhân hay công tác', en:'Business Traveler', zh:'差旅商務人士' },
      desc:{ vi:'Hành lý càng nhẹ càng tốt. Sạc gập 3 trong 1 và pin nam châm là vật bất ly thân.',
             en:'The lighter the bag, the better. Folding chargers and snap-on power are the essentials.',
             zh:'行李越輕越好，折疊充電器與磁吸電源是必備。' },
      picks:['desk-travel','portable-power'] },
    { id:'creator', icon:'camera', age:'25–45',
      name:{ vi:'Nhà sáng tạo ngoài trời', en:'Outdoor Creator', zh:'戶外/影像創作者' },
      desc:{ vi:'Vlog, thể thao, cắm trại. Giá trị cốt lõi là khả năng mở rộng của hệ nam châm.',
             en:'Vlogs, action shots, camping. The core value is how far the magnetic system extends.',
             zh:'Vlog、運動攝影、露營，看重磁吸生態的擴充性。' },
      picks:['accessories','stands-display'] }
  ],

  /* ---- Products (Notion: Products — public fields only) ----
     Placeholder SKUs modeled on market references; replace via Notion. */
  products: [
    /* — Car Magnetic Mounts (6) — */
    { sku:'VMG-B1-Vent', slug:'vent-magnetic-car-mount', status:'published', tier:'B',
      category:'car-mounts', scenarios:['S2'], personas:['commuter'],
      art:'vent', qi:'none', watt:null, mount:['vent'], price:15.9,
      rating:4.6, reviews:87, badge:null,
      name:{ vi:'Giá đỡ nam châm cửa gió VIEMAG', en:'VIEMAG Vent Magnetic Mount', zh:'VIEMAG 出風口磁吸支架' },
      claim:{ vi:'Kẹp cửa gió chắc chắn, gắn máy một chạm khi lên xe.',
              en:'Locks into the vent, docks your phone the moment you get in.',
              zh:'穩固卡入出風口，上車一吸即定位。' } },
    { sku:'VMG-B2-Dash', slug:'dashboard-magnetic-car-mount', status:'published', tier:'A',
      category:'car-mounts', scenarios:['S2'], personas:['commuter'],
      art:'dash', qi:'none', watt:null, mount:['dashboard'], price:19.9,
      rating:4.8, reviews:214, badge:'bestseller',
      name:{ vi:'Giá đỡ nam châm táp-lô VIEMAG', en:'VIEMAG Dashboard Magnetic Mount', zh:'VIEMAG 儀表板磁吸支架' },
      claim:{ vi:'Dẫn đường cả ngày trên táp-lô, phanh gấp vẫn đứng yên.',
              en:'All-day navigation on the dash that stays put under hard braking.',
              zh:'儀表板全日導航，急煞依然穩固。' } },
    { sku:'VMG-B2-Suction', slug:'suction-arm-magnetic-mount', status:'published', tier:'B',
      category:'car-mounts', scenarios:['S2'], personas:['commuter'],
      art:'suction', qi:'none', watt:null, mount:['suction'], price:22.9,
      rating:4.7, reviews:63, badge:null,
      name:{ vi:'Giá đỡ tay dài đế hút chân không VIEMAG', en:'VIEMAG Suction Long-Arm Mount', zh:'VIEMAG 吸盤長臂磁吸支架' },
      claim:{ vi:'Tay đòn dài chỉnh mọi góc nhìn, đế hút bám chắc kính và táp-lô.',
              en:'A long arm for any viewing angle, vacuum base grips glass and dash.',
              zh:'長臂調整任何視角，吸盤緊咬玻璃與儀表板。' } },
    { sku:'VMG-B3-Screen', slug:'screen-clip-magnetic-mount', status:'published', tier:'C',
      category:'car-mounts', scenarios:['S2'], personas:['commuter'],
      art:'clip', qi:'none', watt:null, mount:['screen'], price:24.9,
      rating:4.5, reviews:41, badge:'new',
      name:{ vi:'Giá kẹp màn hình trung tâm VIEMAG', en:'VIEMAG Screen-Edge Magnetic Mount', zh:'VIEMAG 螢幕邊磁吸支架' },
      claim:{ vi:'Kẹp cạnh màn hình trung tâm, không che cửa gió, không dán keo.',
              en:'Clips to the center screen edge — no vents blocked, no adhesive.',
              zh:'夾在中控螢幕邊，不擋出風口、不用貼膠。' } },
    { sku:'VMG-B2-Tape', slug:'tape-magnetic-car-mount', status:'published', tier:'C',
      category:'car-mounts', scenarios:['S2'], personas:['commuter'],
      art:'tape', qi:'none', watt:null, mount:['tape'], price:17.9,
      rating:4.6, reviews:52, badge:null,
      name:{ vi:'Giá đỡ nam châm dán 3M VIEMAG', en:'VIEMAG 3M Tape Magnetic Mount', zh:'VIEMAG 3M 膠貼磁吸支架' },
      claim:{ vi:'Dán phẳng mọi bề mặt bằng keo 3M, lắp trong 30 giây.',
              en:'Mounts on any flat surface with 3M adhesive in 30 seconds.',
              zh:'3M 背膠貼平任何平面，30 秒完成安裝。' } },
    { sku:'VMG-B1-Pro', slug:'pro-antivibration-magnetic-mount', status:'published', tier:'B',
      category:'car-mounts', scenarios:['S2'], personas:['commuter'],
      art:'pro', qi:'none', watt:null, mount:['vent','dashboard'], price:24.9,
      rating:4.9, reviews:98, badge:'bestseller',
      name:{ vi:'Giá đỡ chống rung lực hút mạnh VIEMAG Pro', en:'VIEMAG Pro Anti-Vibration Strong Mount', zh:'VIEMAG Pro 強磁耐震支架' },
      claim:{ vi:'Nam châm N52 và kết cấu chống rung — bằng chứng chất lượng của cả dòng sản phẩm.',
              en:'N52 magnets and an anti-vibration build — the proof piece of the lineup.',
              zh:'N52 強磁與耐震結構，整條產品線的品質證據款。' } },

    /* — Qi2 Car Charging Mounts (4) — */
    { sku:'VMG-B1-Qi2-15W', slug:'vent-qi2-15w-car-charger', status:'published', tier:'B',
      category:'car-chargers', scenarios:['S2'], personas:['commuter'],
      art:'carcharge', qi:'compatible', watt:'15W', mount:['vent'], price:35.9,
      rating:4.7, reviews:76, badge:null,
      name:{ vi:'Giá sạc cửa gió 15W VIEMAG', en:'VIEMAG Vent 15W Wireless Charging Mount', zh:'VIEMAG 出風口 15W 車充支架' },
      claim:{ vi:'Gắn là sạc 15W, thiết kế theo chuẩn Qi2, gió điều hoà hỗ trợ tản nhiệt.',
              en:'Dock and charge at 15W, built to the Qi2 standard, cooled by the vent airflow.',
              zh:'一吸即充 15W，依 Qi2 標準設計，出風口氣流輔助散熱。' } },
    { sku:'VMG-B2-Qi2-15W', slug:'dashboard-qi2-15w-car-charger', status:'published', tier:'A',
      category:'car-chargers', scenarios:['S2'], personas:['commuter'],
      art:'dashcharge', qi:'compatible', watt:'15W', mount:['dashboard'], price:39.9,
      rating:4.8, reviews:158, badge:'bestseller',
      name:{ vi:'Giá sạc táp-lô 15W VIEMAG', en:'VIEMAG Dashboard 15W Wireless Charging Mount', zh:'VIEMAG 儀表板 15W 車充支架' },
      claim:{ vi:'Chủ lực của dòng sạc xe: dẫn đường cả ngày, sạc 15W không quá nóng.',
              en:'The workhorse: all-day navigation with 15W charging that keeps its cool.',
              zh:'車充主力款：全日導航，15W 充電不過熱。' } },
    { sku:'VMG-B1-Qi2-25W-Fan', slug:'qi2-25w-cooled-car-charger', status:'published', tier:'B',
      category:'car-chargers', scenarios:['S2'], personas:['commuter','traveler'],
      art:'fancharge', qi:'testing', watt:'25W', mount:['vent','dashboard'], price:55.9,
      rating:4.9, reviews:34, badge:'new',
      name:{ vi:'Giá sạc 25W tản nhiệt chủ động VIEMAG', en:'VIEMAG 25W Active-Cooling Charging Mount', zh:'VIEMAG 25W 主動散熱車充支架' },
      claim:{ vi:'Sạc nhanh 25W theo chuẩn Qi2.2 với quạt tản nhiệt chủ động — mẫu đầu bảng.',
              en:'25W fast charging built to Qi2.2 with an active cooling fan — the flagship.',
              zh:'依 Qi2.2 標準設計的 25W 快充＋主動散熱風扇，旗艦款。' } },
    { sku:'VMG-B2-Qi2-Long', slug:'long-arm-qi2-car-charger', status:'published', tier:'C',
      category:'car-chargers', scenarios:['S2'], personas:['commuter'],
      art:'suctioncharge', qi:'compatible', watt:'15W', mount:['suction'], price:45.9,
      rating:4.6, reviews:29, badge:null,
      name:{ vi:'Giá sạc tay dài điều chỉnh VIEMAG', en:'VIEMAG Long-Arm Adjustable Charging Mount', zh:'VIEMAG 長臂可調車充支架' },
      claim:{ vi:'Tay đòn dài cho xe có táp-lô sâu, vừa giữ vừa sạc.',
              en:'A long adjustable arm for deep dashboards — hold and charge in one.',
              zh:'深儀表板車型的長臂解法，支撐與充電一次到位。' } },

    /* — Desk & Travel Qi2 Chargers (3) — */
    { sku:'VMG-A1-Qi2', slug:'qi2-desktop-charger', status:'published', tier:'B',
      category:'desk-travel', scenarios:['S3','S1'], personas:['homeoffice'],
      art:'deskcharge', qi:'compatible', watt:'15W', mount:['desktop'], price:35.9,
      rating:4.7, reviews:66, badge:null,
      name:{ vi:'Sạc để bàn VIEMAG', en:'VIEMAG Desktop Wireless Charger', zh:'VIEMAG 單機桌面充電器' },
      claim:{ vi:'Một điểm sạc cố định trên bàn, đặt xuống là sạc.',
              en:'One fixed charging spot on your desk — set the phone down, it charges.',
              zh:'桌面固定充電點，放下即充。' } },
    { sku:'VMG-A2-Desk', slug:'2in1-desk-charging-stand', status:'published', tier:'A',
      category:'desk-travel', scenarios:['S3','S4'], personas:['homeoffice'],
      art:'stand2in1', qi:'compatible', watt:'15W', mount:['desktop'], price:45.9,
      rating:4.8, reviews:112, badge:'bestseller',
      name:{ vi:'Đế sạc 2 trong 1 VIEMAG', en:'VIEMAG 2-in-1 Desk Charging Stand', zh:'VIEMAG 二合一桌面充電座' },
      claim:{ vi:'Điện thoại dựng đứng họp video, tai nghe sạc bên dưới.',
              en:'Phone upright for video calls, earbuds charging below.',
              zh:'手機立式視訊，耳機在下方同步充電。' } },
    { sku:'VMG-A3-Fold', slug:'folding-travel-qi2-charger', status:'published', tier:'B',
      category:'desk-travel', scenarios:['S5','S3'], personas:['traveler','homeoffice'],
      art:'fold', qi:'testing', watt:'15W', mount:['desktop'], price:52.9,
      rating:4.8, reviews:58, badge:'new',
      name:{ vi:'Sạc du lịch gập VIEMAG', en:'VIEMAG Folding Travel Charger', zh:'VIEMAG 折疊旅行充電器' },
      claim:{ vi:'Gập lại bằng lòng bàn tay, mở ra là trạm sạc khách sạn.',
              en:'Folds to palm size, opens into your hotel charging station.',
              zh:'折起一掌大小，展開就是飯店充電站。' } },

    /* — Magnetic Accessories (2) — */
    { sku:'VMG-E1-Ring', slug:'magnetic-adapter-ring-kit', status:'published', tier:'B',
      category:'accessories', scenarios:['S2','S3','S5'], personas:['commuter','creator'],
      art:'ring', qi:'none', watt:null, mount:[], price:9.9,
      rating:4.6, reviews:143, badge:null,
      name:{ vi:'Bộ vòng nam châm chuyển đổi VIEMAG', en:'VIEMAG Magnetic Adapter Ring Kit', zh:'VIEMAG 磁吸轉接環套組' },
      claim:{ vi:'Dán một vòng, điện thoại nào cũng vào được hệ nam châm.',
              en:'Stick on one ring and any phone joins the magnetic system.',
              zh:'貼上一枚轉接環，任何手機都能進入磁吸系統。' } },
    { sku:'VMG-E2-CaseKit', slug:'magnetic-case-ring-bundle', status:'published', tier:'C',
      category:'accessories', scenarios:['S2','S3'], personas:['commuter','homeoffice'],
      art:'case', qi:'none', watt:null, mount:[], price:14.9,
      rating:4.7, reviews:71, badge:null,
      name:{ vi:'Combo ốp lưng + vòng nam châm VIEMAG', en:'VIEMAG Case + Ring Bundle', zh:'VIEMAG 手機殼＋轉接環組合' },
      claim:{ vi:'Ốp bảo vệ kèm vòng nam châm định vị sẵn — tương thích tối đa.',
              en:'A protective case with the magnet ring pre-aligned for maximum grip.',
              zh:'保護殼內建對位磁環，相容性一次到位。' } },

    /* — Future categories (display only, POK-style references) — */
    { sku:'VMG-C1-10K', slug:'magnetic-power-bank-10k', status:'future', tier:'Future',
      category:'portable-power', scenarios:['S5','S2'], personas:['traveler'],
      art:'powerbank', qi:'compatible', watt:'15W', mount:[], price:null,
      rating:null, reviews:0, badge:'soon',
      name:{ vi:'Pin nam châm VIEMAG 10.000mAh', en:'VIEMAG Magnetic Power Bank 10K', zh:'VIEMAG 磁吸行動電源 10K' },
      claim:{ vi:'Hút dán sau máy, sạc không dây khi đang di chuyển — sắp ra mắt.',
              en:'Snaps to the back and charges wirelessly on the move — coming soon.',
              zh:'吸附機背、行進間無線充電，即將推出。' } },
    { sku:'VMG-D1-Stand', slug:'desktop-magnetic-stand', status:'future', tier:'Future',
      category:'stands-display', scenarios:['S3','S4'], personas:['homeoffice','creator'],
      art:'stand', qi:'none', watt:null, mount:['desktop'], price:null,
      rating:null, reviews:0, badge:'soon',
      name:{ vi:'Giá đỡ bàn nam châm VIEMAG', en:'VIEMAG Desktop Magnetic Stand', zh:'VIEMAG 桌面磁吸立架' },
      claim:{ vi:'Nâng máy lên tầm mắt, xoay dọc ngang tuỳ ý — sắp ra mắt.',
              en:'Raises the phone to eye level, rotates portrait to landscape — coming soon.',
              zh:'手機抬升至視線高度、直橫向自由旋轉，即將推出。' } },
    { sku:'VMG-D3-Grip', slug:'creator-tripod-adapter', status:'future', tier:'Future',
      category:'stands-display', scenarios:['S6'], personas:['creator'],
      art:'tripod', qi:'none', watt:null, mount:[], price:null,
      rating:null, reviews:0, badge:'soon',
      name:{ vi:'Ngàm chân máy nam châm VIEMAG', en:'VIEMAG Magnetic Tripod Adapter', zh:'VIEMAG 磁吸腳架轉接座' },
      claim:{ vi:'Một ngàm nam châm nối điện thoại với mọi chân máy 1/4" — sắp ra mắt.',
              en:'One magnetic head connects your phone to any 1/4" tripod — coming soon.',
              zh:'一顆磁吸頭，接上任何 1/4" 腳架，即將推出。' } }
  ],

  /* ---- Quality evidence (Notion: Test Reports — types only; report
          files render only when Approved for Marketing = true) ---- */
  tests: [
    { id:'vibration', icon:'wave',
      name:{ vi:'Kiểm tra rung xóc', en:'Vibration Testing', zh:'震動測試' },
      desc:{ vi:'Mô phỏng mặt đường xấu và phanh gấp trước khi xuất xưởng.',
             en:'Simulates rough roads and hard braking before any unit ships.',
             zh:'出貨前模擬爛路與急煞情境。' } },
    { id:'thermal', icon:'thermo',
      name:{ vi:'Kiểm tra tăng nhiệt', en:'Thermal-Rise Testing', zh:'溫升測試' },
      desc:{ vi:'Theo dõi nhiệt độ suốt chu kỳ sạc để giữ máy luôn mát.',
             en:'Charge-cycle temperature profiling keeps phones cool.',
             zh:'全充電週期溫度監控，手機不燙手。' } },
    { id:'magnetic', icon:'magnet',
      name:{ vi:'Kiểm tra lực hút', en:'Magnetic Force Testing', zh:'磁力測試' },
      desc:{ vi:'Đo lực giữ theo mọi hướng, kể cả khi dùng ốp lưng.',
             en:'Holding force measured in every direction, case-on included.',
             zh:'各方向吸持力實測，含裝殼狀態。' } },
    { id:'lifecycle', icon:'cycle',
      name:{ vi:'Tuổi thọ hút – nhả', en:'Attach-Release Lifecycle', zh:'吸合壽命測試' },
      desc:{ vi:'Hàng nghìn chu kỳ gắn – tháo và kiểm tra khớp xoay.',
             en:'Thousands of dock-release cycles plus hinge endurance.',
             zh:'數千次吸合循環與球頭鉸鏈耐久。' } }
  ],

  /* ---- FAQ (Notion: FAQ) ---- */
  faqs: [
    { id:'no-magnet',
      q:{ vi:'Điện thoại của tôi không có nam châm, dùng được không?',
          en:'My phone has no built-in magnets. Can I still use VIEMAG?',
          zh:'我的手機沒有磁吸功能，可以用嗎？' },
      a:{ vi:'Được. Chỉ cần dán vòng chuyển đổi VIEMAG hoặc dùng ốp lưng nam châm trong bộ phụ kiện, mọi điện thoại đều gắn được lên toàn hệ sản phẩm.',
          en:'Yes. Add a VIEMAG adapter ring or magnetic case from the accessories line and any phone works across the whole system.',
          zh:'可以。貼上 VIEMAG 轉接環或使用磁吸手機殼，任何手機都能使用整個系統。' } },
    { id:'why-ring',
      q:{ vi:'Vì sao cần ốp lưng nam châm hoặc vòng chuyển đổi?',
          en:'Why do I need a magnetic case or adapter ring?',
          zh:'為什麼需要磁吸手機殼或轉接環？' },
      a:{ vi:'Lực hút cần vòng nam châm định vị đúng tâm. Ốp hoặc vòng chuyển đổi đảm bảo vị trí chuẩn để giữ chắc và sạc hiệu quả.',
          en:'Magnetic holding needs a correctly centered ring. A case or adapter ring guarantees alignment for a firm hold and efficient charging.',
          zh:'磁吸需要正確對位的磁環，手機殼或轉接環能確保吸持穩固與充電效率。' } },
    { id:'heat',
      q:{ vi:'Sạc không dây bị ấm máy có bình thường không?',
          en:'Is it normal for the phone to get warm while charging?',
          zh:'無線充電時發熱正常嗎？' },
      a:{ vi:'Ấm nhẹ là bình thường. Sản phẩm VIEMAG đều qua kiểm tra tăng nhiệt; nếu máy nóng bất thường, hãy tháo ốp quá dày và liên hệ CSKH.',
          en:'Mild warmth is normal. Every VIEMAG charger passes thermal-rise testing; if it gets unusually hot, remove overly thick cases and contact support.',
          zh:'微溫屬正常。VIEMAG 充電產品皆通過溫升測試；若異常發燙，請先移除過厚手機殼並聯絡客服。' } },
    { id:'vent',
      q:{ vi:'Loại cửa gió nào không phù hợp với giá đỡ cửa gió?',
          en:'Which car vents are not suitable for vent mounts?',
          zh:'哪些出風口不適合安裝出風口支架？' },
      a:{ vi:'Cửa gió tròn xoay, lá gió quá mảnh hoặc cửa gió điện tử ẩn có thể không giữ chắc. Trường hợp đó nên chọn bản táp-lô hoặc bản dán 3M.',
          en:'Round rotating vents, very thin blades or hidden electronic vents may not hold firmly. Choose the dashboard or 3M tape version instead.',
          zh:'圓形旋轉式、葉片過細或隱藏式電子出風口可能不穩，建議改用儀表板款或 3M 貼片款。' } },
    { id:'tape',
      q:{ vi:'Miếng dán 3M có dùng lại được không?',
          en:'Can the 3M adhesive pad be reused?',
          zh:'3M 貼片可以重複使用嗎？' },
      a:{ vi:'Keo 3M dán chắc nhất ở lần đầu. Khi cần dời vị trí, hãy dùng miếng keo thay thế trong hộp để đảm bảo độ bám.',
          en:'3M adhesive bonds strongest on first application. Use the spare pad included in the box when relocating the mount.',
          zh:'3M 背膠首次黏貼最牢，移位時請使用盒內備用貼片以確保黏著力。' } },
    { id:'warranty',
      q:{ vi:'Bảo hành 12 tháng gồm những gì?',
          en:'What does the 12-month warranty cover?',
          zh:'12 個月保固涵蓋哪些問題？' },
      a:{ vi:'Lỗi vật liệu và lỗi sản xuất trong sử dụng bình thường: nam châm suy yếu bất thường, khớp lỏng, lỗi sạc. Hư hại do rơi vỡ, va đập không thuộc phạm vi bảo hành.',
          en:'Material and manufacturing defects under normal use: abnormal magnet weakening, loose joints, charging failures. Drop or impact damage is not covered.',
          zh:'正常使用下的材料與製造瑕疵：磁力異常衰減、關節鬆動、充電故障。摔落撞擊等人為損壞不在範圍內。' } },
    { id:'doa',
      q:{ vi:'Hàng lỗi khi nhận được đổi mới thế nào?',
          en:'How do I exchange a defective item on arrival?',
          zh:'到貨瑕疵如何換新？' },
      a:{ vi:'Trong 14 ngày kể từ khi nhận hàng, gửi ảnh hoặc video sản phẩm lỗi cho CSKH — chúng tôi đổi mới, không sửa chữa.',
          en:'Within 14 days of delivery, send photos or a short video of the defect to support — we replace, not repair.',
          zh:'到貨 14 天內提供照片或影片給客服，直接換新品、不維修。' } }
  ],

  /* ---- Config: connect forms / shop links later ---- */
  config: {
    shopeeUrl: '#', /* Shopee Vietnam store URL — fill when live */
    dealerEndpoint: '' /* webhook that writes to Notion Dealer Leads — fill when live */
  }
};
